#include "PanicControls.h"
#include "ScoringSelection.h"

#define LEFT_SCORING_LEVEL_SELECTOR_ADDRESS 0x30
#define RIGHT_SCORING_LEVEL_SELECTOR_ADDRESS 0x31
#define SCORING_LEVEL_KEYPAD_INTERRUPT_PIN 0

#define PANIC_CONTROLS_MCP_I2C_ADDRESS 0x20
#define PANIC_CONTROLS_MCP_INTERRUPT_PIN 1 // TODO: Set this

void setup()
{
    XInput.begin();

    PanicControls::init(PANIC_CONTROLS_MCP_I2C_ADDRESS, PANIC_CONTROLS_MCP_INTERRUPT_PIN);
    ScoringSelection::init(LEFT_SCORING_LEVEL_SELECTOR_ADDRESS, RIGHT_SCORING_LEVEL_SELECTOR_ADDRESS, SCORING_LEVEL_KEYPAD_INTERRUPT_PIN);
}

void loop()
{
}